version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/StoryCAD/StoryCAD.csproj"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5

    commit-message:
      prefix: "StoryCAD"

  - package-ecosystem: "nuget"
    directory: "/StoryCADLib/StoryCADLib.csproj"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "StoryCADLib"

  - package-ecosystem: "nuget"
    directory: "/StoryCADTests/StoryCADTests.csproj"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "StoryCADTests"
