# IMPORTANT - Don't forget to bump the .NET version for Install .NET AND StoryCADTests
name: ReleaseBuilder

on:
  workflow_dispatch:
    inputs:
      VersionNumber:
        description: 'Version'
        required: true
        default: '3.1.3.0'

jobs:
  build:
    runs-on: windows-latest
    env:
      Solution_Name: StoryCAD.sln

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    # ─── Version bump ────────────────────────────────────────────────────────────
    - name: Bump appxmanifest version
      shell: pwsh
      run: |
        $ver="${{ github.event.inputs.VersionNumber }}"
        $regex=' Version="\d+\.\d+\.\d+\.\d+"'
        (Get-Content "${{ github.workspace }}\StoryCAD\Package.appxmanifest") `
          -replace $regex, " Version=""$ver""" |
          Set-Content "${{ github.workspace }}\StoryCAD\Package.appxmanifest" -Encoding utf8

    # ─── Cert / env ──────────────────────────────────────────────────────────────
    - name: Decode signing PFX & write .env files
      shell: pwsh
      run: |
        [IO.File]::WriteAllBytes("${{ github.workspace }}\StoryCAD\GitHubActionsWorkflow.pfx",
          [Convert]::FromBase64String("${{ secrets.BASE64_ENCODED_PFX }}"))
        [IO.File]::WriteAllText("${{ github.workspace }}\StoryCAD\.env",      "${{ secrets.ENV }}")
        [IO.File]::WriteAllText("${{ github.workspace }}\StoryCADTests\.env", "${{ secrets.ENV }}")

    # ─── Restore / build ────────────────────────────────────────────────────────
    - name: Restore solution (Release + Debug)
      shell: pwsh
      run: |
        msbuild $env:Solution_Name /t:Restore /p:Configuration=Release
        msbuild $env:Solution_Name /t:Restore /p:Configuration=Debug

    - name: Build StoryCADLib (NuGet)
      shell: pwsh
      run: |
        msbuild StoryCADLib\StoryCADLib.csproj `
          /t:Build `
          /p:Configuration=Release `
          /p:Platform=x64 `
          /p:Version=${{ github.event.inputs.VersionNumber }} `
          /p:NuGetVersion=${{ github.event.inputs.VersionNumber }} `
          /p:AssemblyVersion=${{ github.event.inputs.VersionNumber }}

    - name: Restore and Build StoryCADTests
      run: msbuild StoryCADTests\StoryCADTests.csproj /t:Build /p:Configuration=Debug /p:Platform=x64

    - name: Setup VSTest.console.exe
      uses: darenm/Setup-VSTest@v1.2

    - name: Run StoryCADTests
      run: vstest.console.exe ${{ github.workspace }}\StoryCADTests\bin\x64\Debug\net9.0-windows10.0.22621.0\StoryCADTests.dll /Logger:Console /Platform:x64

    # ─── App packages ───────────────────────────────────────────────────────────
    - name: Create MSIX packages (x64, x86, arm64)
      shell: pwsh
      env:
        Appx_Bundle: Never
        Appx_Package_Build_Mode: SideloadOnly
        Appx_Package_Dir: Packages\
      run: |
        foreach ($plat in 'x64','x86','arm64') {
          msbuild $env:Solution_Name `
            /p:Configuration=Release `
            /p:Platform=$plat `
            /p:UapAppxPackageBuildMode=$env:Appx_Package_Build_Mode `
            /p:AppxBundle=$env:Appx_Bundle `
            /p:PackageCertificateKeyFile="${{ github.workspace }}\StoryCAD\GitHubActionsWorkflow.pfx" `
            /p:PackageCertificateKeyFile="${{ github.workspace }}\StoryCAD\GitHubActionsWorkflow.pfx" `
            /p:AppxPackageDir="$env:Appx_Package_Dir" `
            /p:GenerateAppxPackageOnBuild=true `
            /p:NuGetVersion=${{ github.event.inputs.VersionNumber }} `
            /p:AssemblyVersion=${{ github.event.inputs.VersionNumber }}
        }

    - name: Remove PFX
      shell: pwsh
      run: Remove-Item -path "${{ github.workspace }}\StoryCAD\GitHubActionsWorkflow.pfx"

    - name: Run MSIX cleaner
      shell: pwsh
      run: >
        ${{ github.workspace }}\.github\workflows\MSIX.ps1
        -TargetDirectory "${{ github.workspace }}\StoryCAD\Packages"

    # ─── NuGet repack ───────────────────────────────────────────────────────────
    - name: Repack StoryCADLib with runtime binaries & Assets
      shell: pwsh
      run: |
        # 1. Find the release .nupkg
        $allNupkg = Get-ChildItem -Path "${{ github.workspace }}" -Filter "StoryCADLib*.nupkg" -Recurse
        $releasePkg = $allNupkg | Where-Object FullName -Match "\\Release\\" | Select-Object -First 1

        # 2. Unzip to temp
        $tempDir = Join-Path $env:TEMP ("NuPkg_" + [guid]::NewGuid())
        Expand-Archive -Path $releasePkg.FullName -DestinationPath $tempDir -Force

        # 3. Copy your compiled binaries
        $binSrc = "${{ github.workspace }}\StoryCADLib\bin\x64\Release\net8.0-windows10.0.22621.0"
        $libDir = Join-Path $tempDir "lib\net8.0-windows10.0.22621"
        New-Item -ItemType Directory -Force -Path $libDir | Out-Null
        Copy-Item "$binSrc\*" -Destination $libDir -Recurse -Force

        # 4. Copy your Assets folder into a StoryCADLib sub-folder there
        $assetsSrc = "${{ github.workspace }}\StoryCADLib\Assets"
        $assetsDest = Join-Path $libDir "StoryCADLib"
        New-Item -ItemType Directory -Force -Path $assetsDest | Out-Null
        Copy-Item "$assetsSrc\*" -Destination $assetsDest -Recurse -Force

        # 5. Re-zip and overwrite original
        $outPkg = Join-Path $env:TEMP ("updated_" + $releasePkg.Name)
        Compress-Archive -Path (Join-Path $tempDir '*') -DestinationPath $outPkg -Force
        Move-Item -Path $outPkg -Destination $releasePkg.FullName -Force

        # 6. Cleanup
        Remove-Item -Recurse -Force $tempDir

    - name: Move repacked StoryCADLib to Packages
      shell: pwsh
      run: |
        Get-ChildItem -Path "${{ github.workspace }}\StoryCADLib\bin\Release" -Filter "StoryCADLib*.nupkg" |
          Move-Item -Destination "${{ github.workspace }}\StoryCAD\Packages" -Force

    # ─── Help file & zipping ───────────────────────────────────────────────────
    - name: Write install instructions
      shell: pwsh
      run: |
        $file = "${{ github.workspace }}\StoryCAD\Packages\Install Instructions.txt"

        @(
          "Hello, Thank you for using StoryCAD Release ${{ github.event.inputs.VersionNumber }}",
          "",
          "1) Open StoryCAD.cer to launch the certificate import wizard.",
          "2) Choose Local Machine store location and click Next.",
          "3) Select Place all certificates in the following store → Trusted People, then OK.",
          "4) Click Finish.",
          "",
          "Open Packages\ and run StoryCAD Release x64.msix (recommended).",
          "",
          "See what's changed:",
          "https://github.com/StoryBuilder-org/StoryCAD/releases/tag/${{ github.event.inputs.VersionNumber }}"
        ) | Set-Content -Path $file -Encoding UTF8

    - name: Zip Packages → Release.zip
      uses: thedoctor0/zip-release@master
      with:
        type: zip
        filename: Release.zip
        path: ${{ github.workspace }}\StoryCAD\Packages\

    # ─── Upload artefacts ──────────────────────────────────────────────────────
    - name: Upload MSIX packages
      uses: actions/upload-artifact@v4
      with:
        name: StoryCAD
        path: ${{ github.workspace }}\StoryCAD\Packages\*
        compression-level: 9
        include-hidden-files: true

    - name: Upload repacked NuGet
      uses: actions/upload-artifact@v4
      with:
        name: repacked-nuget-package
        path: ${{ github.workspace }}\StoryCADLib\bin\Release\StoryCADLib*.nupkg

    # ─── Tag & GitHub release ─────────────────────────────────────────────────
    - name: Configure Git
      shell: pwsh
      run: |
        git config user.name  "Release Builder"
        git config user.email "jake@storybuilder.org"

    - name: Tag commit
      shell: pwsh
      run: |
        git tag -a "${{ github.event.inputs.VersionNumber }}" -m "${{ github.event.inputs.VersionNumber }}"
        git push origin "${{ github.event.inputs.VersionNumber }}"

    - name: Publish GitHub release
      uses: softprops/action-gh-release@v1
      with:
        files: Release.zip
        tag_name: ${{ github.event.inputs.VersionNumber }}
        draft: false
        fail_on_unmatched_files: true
        generate_release_notes: false
        token: ${{ secrets.GitHubToken }}
